export interface Notes {
  id?: string;               // Maps from MongoDB _id
  courseCode: string;
  lessonCode: string;
  selectedText?: string;     // Optional as it defaults to an empty string
  timestamp: number;
  note: string;
  userId: string;            // MongoDB ObjectId represented as a string
  createdAt?: string;        // Generated by { timestamps: true }
  updatedAt?: string;        // Generated by { timestamps: true }
}
