export const ENDPOINTS = {
    LOGIN: '/auth/login',
    LOGOUT: 'auth/logout',
    REGISTER: 'auth/register',
    GET_USER: 'auth/profile',
    EDIT_USER: 'auth/editProfile',
    UPDATE_PASSWORD: '/auth/changePassword',
    FORGOT_PASSWORD: '/forgot-password',
    GETALLCOURSES : '/courses',
    GETCOURSEBYID : '/course/code',
    GETLESSONSBYCOURSE : '/course/lessons',
    GETINSTRUCTOR : '/course/instructor',
    GETREWIVE : '/course/reviews',
    HOME: '/home',
    GETLESSSONBYID : '/course',
    TRANSCRIPT : '/transcript',
    ENROLLMENT : "/enrollment",
    BOOKMARK : "/bookmark",
    NOTES: "/notes"
} as const;