export const Strings = {
     create_account: "Create Account",
     join_learn_flow: "Join LearnFlow and start Learning",
     full_name: "Full Name",
     email: "Email",
     password: "Password",
     confirm_password: "Confirm Password",
     password_lenghth: "Password must contain at least 8 characters, one uppercase letter, one lowercase letter, one number, and one special character.",
     remember_me: "Remember Me",
     login: "Login",
     already_have_acc: "Already have an account?",
     register: "Register",
     dont_have_any_account: "Don't have an account?",
     or: "OR",
     google_login: "Continue with Goolge",
     apple_login: "Continue with Apple",
     i_aggre_to: "I agree to the",
     terms: "Terms",
     and: "and",
     policy: "Privacy Policy",
     forgot_password: "Forgot Password?",
     profile: "Profile",
     phone_number: "Phone Number",
     joined_date: "Joined Data",
     account: "Account",
     update_your_persn: "Update your personla information",
     update_your_pass: "Update your account password",
     read_policy: "Read our privacy policy",
     personal_infrom: "Personal Infromation",
     date_of_birt: "Date of Birth",
     save_changes: "Save Changes",
     cancel: "Cancel",
     edit_profile: "Edit Profile",
     logout: "Logout",
     change_password: "Change Password",
     current_password: "Current Password",
     new_password: "New Password",
     conf_new_pass: "Confirm New Password",
     update_password: "Update Password",
     security_dont_share: "For your security, please dont share your password with anyone",
     change_your_password: "Change Your Password",
     tap_to_change_img: "Tap on the photo to change",
     welcome: "Welcome back,",
     keep_learning: "Keep learing, Keep growing!",
     search_home: "Search for Courses,Lessons...",
     contine_learning: "Continue Learning",
     view_all: "View All",
     recommended_for_you: "Recommended for You",
     categories: "Categories",
     lessons: "Lessons",
     all: "All",
     beginner: "Beginner",
     intermediate: "Intermediate",
     advanced: "Advanced",
     cousrces: "Courses",
     search_course: "Search for Courses",
     filter_courses: "Filter Courses",
     level: "Level",
     enrolled: "enrolled",
     overview: "Overview",
     curriculum: "Curriculum",
     instructor: "Instructor",
     reviews: "Reviews",
     enroll_now: "Enroll Now",
     total_price: "Total Price",
     what_you_will_learn: "what You Will Learn",
     students_enroller: "Students enrolled",
     my_learning: "My Learning",
     in_progress: "In Progress",
     completed: "Completed",
     bookmark: "Bookmarks",
     make_payment: "Make a Payment",
     complete_payment: "Complete your Payment",
     payment: "Payment",
     checkout: "Checkout",
     not_enrolled: "Yet to enroll",
     my_notes: "My Notes",
     add_notes: "Add Notes",
     note: "Note",
     edit_notes: "Edit Notes",
     save: "Save",
     Time_stamp: "TIMESTAMP ",
     write_your_obs: "Write youe Observation",
     all_lessons: "All Lessons",
     my_cousrses: "My Cousrses",
     my_bookmarked: "My Bookedmarked Cousrses",
     email_you_verify: "Verify Your Email",
     email_verify: "Verify Email",
     resend_code : "Resend Code",
     sent_to_email: "We've sent a 4-digit verification code to",
     reset_your_password : "Reset Your Password",
     reset_password : "Reset Password",
     enter_email_address : "Enter Email address and we'll send \n a link to reset your password.",
     send : "Send",
     token : "Token",
     meaning : "Meaning"
}