export  const Strings = {
     create_account : "Create Account",
     join_learn_flow : "Join LearnFlow and start Learning",
     full_name : "Full Name",
     email : "Email",
     password: "Password",
     confirm_password :"Confirm Password",
     password_lenghth : "Password must contain at least 8 characters, one uppercase letter, one lowercase letter, one number, and one special character.",
     remember_me : "Remember Me",
     login : "Login",
     already_have_acc : "Already have an account?",
     register : "Register",
     dont_have_any_account : "Don't have an account?",
     or : "OR",
     google_login : "Continue with Goolge",
     apple_login : "Continue with Apple",
     i_aggre_to :"I agree to the",
     terms: "Terms",
     and : "and",
     policy : "Privacy Policy",
     forgot_password : "Forgot Password?",
     profile : "Profile",
     phone_number : "Phone Number",
     joined_date : "Joined Data",
     account : "Account",
     update_your_persn : "Update your personla information",
     update_your_pass : "Update your account password",
     read_policy : "Read our privacy policy",
     personal_infrom : "Personal Infromation",
     date_of_birt : "Date of Birth",
     save_changes : "Save Changes",
     cancel : "Cancel",
     edit_profile : "Edit Profile",
     logout : "Logout",
     change_password: "Change Password",
     current_password : "Current Password",
     new_password : "New Password",
     conf_new_pass : "Confirm New Password",
     update_password : "Update Password",
     security_dont_share : "For your securit, please dont share your password with anyone",
     change_your_password : "Change Your Password",
     tap_to_change_img : "Tap on the photo to change",
     welcome : "Welcome back,",
     keep_learning : "Keep learing, Keep growing!",
     search_home : "Search for Courses,Lessons...",
     contine_learning : "Continue Learning",
     view_all : "View All",
     recommended_for_you : "Recommended for You",
     categories :"Categories",
     lessons :"Lessons",
     beginner : "Beginner",
     intermediate :"Intermediate",
     advance :"Advance",
     cousrces : "Courses",
     search_course : "Search for Courses",
}