export  const Strings = {
     create_account : "Create Account",
     join_learn_flow : "Join LearnFlow and start Learning",
     full_name : "Full Name",
     email : "Email",
     password: "Password",
     confirm_password :"Confirm Password",
     password_lenghth : "Password must contain at least 8 characters, one uppercase letter, one lowercase letter, one number, and one special character.",
     remember_me : "Remember Me",
     login : "Login",
     already_have_acc : "Already have an account?",
     register : "Register",
     dont_have_any_account : "Don't have an account?",
     or : "OR",
     google_login : "Continue with Goolge",
     apple_login : "Continue with Apple",
     i_aggre_to :"I agree to the",
     terms: "Terms",
     and : "and",
     policy : "Privacy Policy",
     forgot_password : "Forgot Password?",
}